map_type: costmap

obstacle_range: 2
raytrace_range: 5


min_particles: 25
max_particles: 200
transform_tolerance: 0.2



robot_radius: 0.5 
inflation_radius: 0.75

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /iamfiscus_bot/laser/scan, marking: true, clearing: true}
