map_type: costmap

obstacle_range: 1.5
raytrace_range: 4.0


min_particles: 25
max_particles: 200
transform_tolerance: 0.2



robot_radius: 0.3 
inflation_radius: 0.65

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /iamfiscus_bot/laser/scan, marking: true, clearing: true}
